  GNU nano 4.9.3                                                                          docker-compose.yml
version: "3.7"
services:
  app:
    build: .
    restart: always
  nginx:
    image: shiphp/nginx-env
    restart: always
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=app


